### PR TITLE
Change the markup to use class, use better names for css classes, fix eslint errors, change font for the grave page and more

### PR DESCRIPTION
**Pull request by dumptyd**

### CODE REVIEW

**Comment by dumptyd** [comment]
@avinassh please redeploy the current version.

**Comment by avinassh** [comment]
@dumptyd will do in night. I have lost access to Surge and auth is failing.

**Comment by avinassh** [comment]
damn, I forgot to make release again. I am doing it now.

**Comment by avinassh** [comment]
did now 😄 

I am really sorry for taking so much time. Got busy into other stuff. 

I will try adding travis integration soon. or if you have time, look into it pls #28

**Pull request merged**
