### PR TITLE
Add a graveyard. Resolves #5

### LINKED ISSUE #5: Show all the graves on index page, a graveyard, if you will

### PR DESCRIPTION
**Pull request by dumptyd**

### CODE REVIEW

**Comment by oxalorg** [comment]
WAT DA FREAK? DID YOU JUST REMOVE SAKURA FROM THERE?

**Comment by dumptyd** [comment]
Lol no. It's still there.

**Comment by oxalorg** [comment]
Your body background color isn't `#fff` on custom cemetries.

Also the front page doesn't look good imho. I like it better with only @avinassh 's grave.

**Comment by dumptyd** [comment]
I didn't forget, I just thought well it was like this before so why change it lol. And yeah, sure man.

**Pull request merged**
