### PR TITLE
Add Frag

### PR DESCRIPTION
**Pull request by frag-o-matic**
Add gravestone for frag-o-matic

### CODE REVIEW

**Comment by avinassh** [comment]
Everyone just copied the first sentence from my tombstone: `Here lies X, in rest, finally.` I am gonna reject new PRs with these. Please edit. 

Existing ones will be edited soon. 

Despite being dead, people don't stop plagiarism 😡

**Comment by frag-o-matic** [comment]
Despite being dead, people don't stop plagiarism 😡
kaapi-pashte mera janam siddha aadhikaar hai, aur me isse ka durupyog zarror karunga :xy:

**Comment by avinassh** [comment]
I am not accepting this PR till that line is changed.

**Comment by frag-o-matic** [comment]
> I am not accepting this PR till that line is changed.

and I'm not willing to have my right to self-expression infringed upon :reeee: 
just because someone happened to arrange a bunch of words in a certain way, it shouldn't preclude me from doin' the same.

**Comment by avinassh** [comment]
ehh no.. I closed before merging.

**Comment by avinassh** [comment]
Now done.

😡

**Pull request merged**
